# 📓 Tarea Sesión 22

## Ejemplos de arrays con funciones

In [1]:
import numpy as np

# arrays a partir de lista.
lista1 = [10, 20, 30, 40, 50]
arr1 = np.array(lista1)
print("Arrays a parti de lista:")
print(arr1)


# arrays de ceros
arr_zeros = np.zeros(5)
print("Arrays de ceros:")
print(arr_zeros)


# array de unos (Matriz:2x3)
arr_unos = np.ones((2, 3))
print("Arrays de unos:")
print(arr_unos)

# Array con arange
arr_arange = np.arange(0, 31, 3)
print("Array con arange:")
print(arr_arange)

# Array con linspace
arr_lins = np.linspace(1, 10, 5)
print(" Array con linspace:")
print(arr_lins)

# Array con valores randoms
arr_random = np.random.rand(4,3)
print("Array con valores random:")
print(arr_random)

# Array identidad
arr_eye = np.eye(5)
print("Array identidad:")
print(arr_eye)

Arrays a parti de lista:
[10 20 30 40 50]
Arrays de ceros:
[0. 0. 0. 0. 0.]
Arrays de unos:
[[1. 1. 1.]
 [1. 1. 1.]]
Array con arange:
[ 0  3  6  9 12 15 18 21 24 27 30]
 Array con linspace:
[ 1.    3.25  5.5   7.75 10.  ]
Array con valores random:
[[0.70940377 0.37461145 0.76906464]
 [0.91547467 0.94822976 0.91717184]
 [0.41357064 0.63094442 0.024148  ]
 [0.90638135 0.83811642 0.91003687]]
Array identidad:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## 🆚 Comparación con listas.

In [ ]:
# Lista normal de python
lista = [10, 20, 30, 40, 50]
# array en numpy
x = np.array(lista)
# impresión
print("Lista original: ",lista)
print("array numpy: ",x)

# Multiplicación: diferentes comportamientos
print("Lista *2: ", lista*2)
print("Array *2: ", x*2)

# suma de 10 a cada elemento
print("Lista + 10 → Error? Prueba con list comprehension:")
print("print mediante for: ", [(x+10) for x in lista])
print("Array + 10 : ",  x +10)

# Velocidad (ejemplo pequeño)
import time

lista_grande = list(range(100_000_000))
array_grande = np.array(lista_grande)

# Multiplicar por 2 con lista
start = time.time()
lista_doble = [x * 2 for x in lista_grande]
end = time.time()
print(f"Tiempo con lista: {end - start:.4f} seg")

# Multiplicar por 2 con array
start = time.time()
array_doble = array_grande * 2
end = time.time()
print(f"Tiempo con array: {end - start:.4f} seg")

## 4. Uso de propiedades `shape` `size` `ndim` `dtype`

In [ ]:
# crear array de 2 dimensiones
matriz = np.array([[1, 2, 3],
                   [4, 5, 6]])

print("Matriz: \n", matriz)
print("Shape (forma):\n", matriz.shape)
print("Número total de elementos:\n", matriz.size)
print("Número de dimensiones:", matriz.ndim)
print("Tipo de datos", matriz.dtype)

# Cambiar tipo de datos
matriz_float = matriz.astype(float)
print("Matriz:\n", matriz_float)
print("Tipos de datos: ", matriz_float.dtype)