In [20]:
import numpy as np

np.__version__

'2.3.3'

In [21]:
np.random.seed(42)

----
# 🔹 1. Conjuntos de datos aleatorios + estadísticas

In [30]:
# Ejemplo 1
data1 = np.random.rand(50)
print(data1)
print("Media aritmetica:",np.mean(data1))
print("Mediana:", np.median(data1))
print("Desviación estandar:", np.std(data1))
print("Valor minimo:", np.min(data1))
print("Valor maximo:", np.max(data1))

[0.05168172 0.53135463 0.54063512 0.6374299  0.72609133 0.97585208
 0.51630035 0.32295647 0.79518619 0.27083225 0.43897142 0.07845638
 0.02535074 0.96264841 0.83598012 0.69597421 0.40895294 0.17329432
 0.15643704 0.2502429  0.54922666 0.71459592 0.66019738 0.2799339
 0.95486528 0.73789692 0.55435405 0.61172075 0.41960006 0.24773099
 0.35597268 0.75784611 0.01439349 0.11607264 0.04600264 0.0407288
 0.85546058 0.70365786 0.47417383 0.09783416 0.49161588 0.47347177
 0.17320187 0.43385165 0.39850473 0.6158501  0.63509365 0.04530401
 0.37461261 0.62585992]
Media aritmetica: 0.45708518883345484
Mediana: 0.47382279993394544
Desviación estandar: 0.27306715205443444
Valor minimo: 0.014393488629755868
Valor maximo: 0.9758520794625346


In [32]:
# Ejemplo 2
data2 = np.random.randn(100)
print(data2)
print("Media aritmetica:",np.mean(data2))
print("Mediana:", np.median(data2))
print("Desviación estandar:", np.std(data2))
print("Valor minimo:", np.min(data2))
print("Valor maximo:", np.max(data2))

[ 1.45114361  0.95927083  2.15318246 -0.76734756  0.87232064  0.18334201
  2.18980293 -0.80829829 -0.83972184 -0.59939265 -2.12389572 -0.52575502
 -0.75913266  0.15039379  0.34175598  1.87617084  0.95042384 -0.57690366
 -0.89841467  0.49191917 -1.32023321  1.83145877  1.17944012 -0.46917565
 -1.71313453  1.35387237 -0.11453985  1.23781631 -1.59442766 -0.59937502
  0.0052437   0.04698059 -0.45006547  0.62284993 -1.06762043 -0.14237949
  0.12029563  0.51443883  0.71161488 -1.12464209 -1.53411417  1.27767682
  0.33231401 -0.74848654  1.55115198  0.11567463  1.17929718  0.06751848
  2.06074792  1.75534084 -0.24896415  0.97157095  0.64537595  1.36863156
 -0.96492346  0.68605146  1.05842449 -1.75873949 -1.18325851 -2.03923218
 -0.26940683  0.71754226  1.50235705  0.07409478  1.62861555 -1.38010146
 -1.70338244 -0.0555477   0.38406545 -0.03269475 -2.0674421  -0.08912004
 -1.3044695   0.66967255  0.36659825 -0.93987979 -0.51386692 -1.05921352
 -0.0626791   0.95514232 -0.98572605  0.50404652 -0

In [33]:
# Ejemplo 3
data3 = np.random.randint(0, 100, size=30)
print(data3)
print("Media aritmetica:",np.mean(data3))
print("Mediana:", np.median(data3))
print("Desviación estandar:", np.std(data3))
print("Valor minimo:", np.min(data3))
print("Valor maximo:", np.max(data3))

[89 27 86 77 87  1 25 13 58 55  6  2 22 17 37 98 14 63 88 27 73 38 56 16
 85 89 43 24 16 12]
Media aritmetica: 44.8
Mediana: 37.5
Desviación estandar: 31.13240541086838
Valor minimo: 1
Valor maximo: 98


In [34]:
# Ejemplo 4 (distribución uniforme en rango distinto
data4 = np.random.uniform(-10, 10, size=40)
print(data4)
print("Media aritmetica:",np.mean(data4))
print("Mediana:", np.median(data4))
print("Desviación estandar:", np.std(data4))
print("Valor minimo:", np.min(data4))
print("Valor maximo:", np.max(data4))

[ 1.87184907  3.58204638  5.78342477 -0.03115602 -8.26159424  0.74213084
  1.73682236  4.90878948 -1.36680908 -7.44839394 -4.32448188 -2.73835407
  2.91834483  1.41556609 -2.87806548  9.73030498  2.11549639 -5.25546417
 -7.96435055 -6.94281722 -5.08084543 -6.78637253 -6.26865952 -4.29809663
 -6.53252809  7.93530849 -8.39532509  0.49022779 -1.79206346  9.64757234
 -7.75922196 -2.04288802  9.38940867  7.31014252  6.34144142 -4.84194346
 -6.58224825  3.3728644   8.58751978  1.13525786]
Media aritmetica: -0.46442901578419465
Mediana: -0.6989825484126335
Desviación estandar: 5.655740339622451
Valor minimo: -8.395325086767155
Valor maximo: 9.730304975859593


In [35]:
# Ejemplo 5 (normal con media y sigma diferente
data5 = np.random.normal(loc=20, scale=5, size=60)
print(data5)
print("Media aritmetica:",np.mean(data5))
print("Mediana:", np.median(data5))
print("Desviación estandar:", np.std(data5))
print("Valor minimo:", np.min(data5))
print("Valor maximo:", np.max(data5))

[11.65297359 22.71680096 16.68688121 22.85299334 16.18370422 10.9755895
 11.86228781 20.24042473 21.29861251 15.47841687 23.19296229 11.69239969
 19.66960101 13.944919   16.74081946 20.23699336 15.69793317 18.07722228
 25.03146405 17.11554065 24.17846056 14.35146573 22.64902089 27.2078431
  7.6417775  16.01552372 22.88536064 18.98477307 21.85572937 16.98007407
 20.43294894 19.22161382 25.83891031 21.27210422 21.68801331 17.94061517
 17.56196888 17.83720906 21.97226071 17.8950776  21.44887428 30.37700399
 24.35562352 18.36988234 26.00606961 17.95962313  9.80937732 14.95956845
 10.64604039 18.24243258 20.0920919  28.38218656 21.63463687 18.90449736
 24.14702791  8.94432345 21.17807279 23.85432597 12.60706877 25.71877022]
Media aritmetica: 19.05661312954375
Mediana: 19.10319344641232
Desviación estandar: 4.966121908014207
Valor minimo: 7.6417774993635526
Valor maximo: 30.377003993227195


----
# 🔹 2. Matriz 5x5 y análisis por axis

In [40]:
import numpy as np

np.random.seed(42)

# Matriz 5x5
M = np.random.randint(1, 20, (5, 5))
print("Matriz 5x5:\n", M)

# Sumas
print("Suma por filas (axis=1):", np.sum(M, axis=1))
print("Suma por columnas (axis=0):", np.sum(M, axis=0), "\n")

# Medias
print("Media por filas (axis=1):", np.mean(M, axis=1))
print("Media por columnas (axis=0):", np.mean(M, axis=0), "\n")

# Mínimos
print("Mínimo por filas (axis=1):", np.min(M, axis=1))
print("Mínimo por columnas (axis=0):", np.min(M, axis=0), "\n")

# Máximos
print("Máximo por filas (axis=1):", np.max(M, axis=1))
print("Máximo por columnas (axis=0):", np.max(M, axis=0))


Matriz 5x5:
 [[ 7 15 11  8  7]
 [19 11 11  4  8]
 [ 3  2 12  6  2]
 [ 1 12 12 17 10]
 [16 15 15 19 12]]
Suma por filas (axis=1): [48 53 25 52 77]
Suma por columnas (axis=0): [46 55 61 54 39] 

Media por filas (axis=1): [ 9.6 10.6  5.  10.4 15.4]
Media por columnas (axis=0): [ 9.2 11.  12.2 10.8  7.8] 

Mínimo por filas (axis=1): [ 7  4  2  1 12]
Mínimo por columnas (axis=0): [ 1  2 11  4  2] 

Máximo por filas (axis=1): [15 19 12 17 19]
Máximo por columnas (axis=0): [19 15 15 19 12]


# 🎲 3. Simulación de 1000 lanzamientos de dado

In [43]:
lanzamientos = np.random.randint(1, 7, size = 1000)
valores, conteos = np.unique(lanzamientos, return_counts =True)
porcentajes = conteos / 1000 * 100

print("Resultados de 1000 lanzamientos:")
print("Caras:", valores)
print("Frecuencias:", conteos)
print("Porcentajes:", porcentajes)
    

Resultados de 1000 lanzamientos:
Caras: [1 2 3 4 5 6]
Frecuencias: [159 173 137 183 177 171]
Porcentajes: [15.9 17.3 13.7 18.3 17.7 17.1]


# 🔎 Conclusión:

In [44]:
# rand → números uniformes entre 0 y 1
a = np.random.rand(5)

# randn → números con distribución normal media 0, std 1
b = np.random.randn(5)

# randint → enteros aleatorios en un rango
c = np.random.randint(1, 10, size=5)

print(a)
print(b)
print(c)

[0.77671056 0.06536616 0.48757119 0.0336136  0.0626532 ]
[-2.42424026  0.8840454   0.7368439  -0.28132756  0.06699072]
[7 5 8 9 5]


- **`rand`**: útil cuando necesitas generar números con **distribución uniforme entre 0 y 1**. Ideal para simular proporciones, probabilidades o cualquier variable que deba ser uniformemente distribuida.

- **`randn`**: se usa cuando ocupas datos con **distribución normal (media 0 y varianza 1)**. Muy útil en modelos estadísticos, ruido gaussiano o cualquier proceso que siga una distribución normal.

- **`randint`**: es la mejor opción cuando necesitas **valores enteros**, como simulaciones de dados, selección de índices, generación de IDs o cualquier proceso discreto.