## 🧮 Tarea
Entrega un notebook llamado **`numpy_broadcasting.ipynb`** que incluya **al menos 3 ejemplos propios** de operaciones con broadcasting. Ideas:
- Resta de medias por columna/filas, escalado por vector.
- Generar una **malla** de coordenadas `X, Y` y evaluar una función `f(X,Y)`.
- Estandarizar por filas en lugar de columnas.
- Aplicar un vector de pesos por columna a una matriz de datos.

💡 Incluye una breve explicación de por qué el broadcasting funciona en cada ejemplo (formas y ejes).

In [3]:
import numpy as np
np.random.seed(41352)
np.__version__

'2.3.3'

# Ejercicio 1 Generacion de matrix 2x2 medicante funcion

In [7]:
#Crear una malla de coordenadas X, Y
x = np.array([1,2,3,4,5])
print (x.shape)

y= np.array ([20,22,24,26,28,30])
print (y.shape)

(5,)
(6,)


In [8]:
#Ahora le vamos aplicar el newaxis
x = x[:, np.newaxis]
print (x.shape)

y = y[np.newaxis, :]
print (y.shape)

(5, 1)
(1, 6)


In [10]:
#Hecho eso ahora si podemos operarlas, la funcion sera f(x,y) = x^2 + 5y
z = x**2 + 5*y
print (z)

[[101 111 121 131 141 151]
 [104 114 124 134 144 154]
 [109 119 129 139 149 159]
 [116 126 136 146 156 166]
 [125 135 145 155 165 175]]


# Estandarizacion por renglones

In [18]:
X = np.random.randint(1, 250, size=(5, 5)).astype(float)
print (X)
#En una matriz 2x2 el renglo esta dadl por axis=1
media = X.mean(axis=1)
estandar = X.std(axis=1)
matrix_normalizada = (X - media)/estandar
print (matrix_normalizada)

[[ 18. 210. 177. 178. 214.]
 [177. 110. 142. 178.  82.]
 [228. 220.  44. 245. 111.]
 [148.  92.  32. 194.  55.]
 [187.  22. 126.  46. 183.]]
[[-1.95369477  1.92184472  0.09421562  1.23811562  1.482005  ]
 [ 0.24317559 -0.73999007 -0.35139881  1.23811562 -0.451045  ]
 [ 0.94783211  2.1880282  -1.59911923  2.36215013 -0.02635977]
 [-0.15751146 -1.21912034 -1.75190132  1.50654177 -0.84644159]
 [ 0.38134353 -3.08240469 -0.55510827 -0.97640012  1.02803113]]


# Aplicar un vector de pesos por columna a una matriz de datos.

In [21]:
#Establecemos una matriz de datos y un vector
matriz_datos = np.array ([
    [80, 70, 90],
    [90, 85, 95],
    [60, 75, 80],
    [70, 65, 75]
])
vector_peso = np.array([2.5, 5, 7.5])

matriz_peso =  matriz_datos * vector_peso
print (matriz_peso)

[[200.  350.  675. ]
 [225.  425.  712.5]
 [150.  375.  600. ]
 [175.  325.  562.5]]
